# Generated by Django 5.2.7 on 2025-10-22 17:55

import django.db.models.deletion
# ESTA LÍNEA ES CRUCIAL PARA CORREGIR EL ERROR DE FECHA
from datetime import date 
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discapacidad',
            options={'verbose_name_plural': 'Discapacidades'},
        ),
        migrations.AlterModelOptions(
            name='etnia',
            options={'verbose_name_plural': 'Etnias'},
        ),
        migrations.AlterModelOptions(
            name='municipio',
            options={'verbose_name_plural': 'Municipios'},
        ),
        migrations.AlterModelOptions(
            name='ocupacion',
            options={'verbose_name_plural': 'Ocupaciones'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name_plural': 'Países'},
        ),
        migrations.AddField(
            model_name='discapacidad',
            name='nombre',
            field=models.CharField(default='SIN DEFINIR', max_length=150, unique=True, verbose_name='Tipo de Discapacidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etnia',
            name='nombre',
            field=models.CharField(default='SIN DEFINIR', max_length=100, unique=True, verbose_name='Nombre de la Etnia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipio',
            name='nombre',
            field=models.CharField(default='SIN DEFINIR', max_length=100, verbose_name='Nombre del Municipio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ocupacion',
            name='nombre',
            field=models.CharField(default='SIN DEFINIR', max_length=150, unique=True, verbose_name='Nombre de la Ocupación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='discapacidades',
            field=models.ManyToManyField(blank=True, to='Clinica.discapacidad', verbose_name='Tipos de Discapacidad'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='etnia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Clinica.etnia', verbose_name='Pertenencia Étnica'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_nacimiento',
            # VALOR CORREGIDO: Usa un objeto date válido en Python
            field=models.DateField(default=date(2000, 1, 1), verbose_name='Fecha de Nacimiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='identificacion',
            # CORREGIDO: Valor único para evitar error de unicidad
            field=models.CharField(default='999999999', max_length=20, unique=True, verbose_name='Nro. Identificación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='nacionalidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Clinica.pais', verbose_name='País de Nacimiento'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='ocupacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Clinica.ocupacion'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='primer_apellido',
            field=models.CharField(default='SIN DEFINIR', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='primer_nombre',
            field=models.CharField(default='SIN DEFINIR', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='residencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Clinica.municipio', verbose_name='Municipio de Residencia'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería')], default='CC', max_length=5, verbose_name='Tipo de Documento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pais',
            name='codigo_iso',
            field=models.CharField(default='NA', max_length=3, unique=True, verbose_name='Código ISO 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pais',
            name='nombre',
            field=models.CharField(default='SIN DEFINIR', max_length=100, unique=True, verbose_name='Nombre del País'),
            preserve_default=False,
        ),
    ]