# Generated by Django 5.2.7 on 2025-10-26 23:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica', '0002_alter_discapacidad_options_alter_etnia_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comunidad_Etnica',
        ),
        migrations.DeleteModel(
            name='Contacto_Servicio_Salud',
        ),
        migrations.DeleteModel(
            name='Diagnostico',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='discapacidades',
        ),
        migrations.DeleteModel(
            name='Enfermedad_Huerfana',
        ),
        migrations.DeleteModel(
            name='Entidad_Prestadora_Salud',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='etnia',
        ),
        migrations.DeleteModel(
            name='Modalidad_Realizacion_Tecnologia_Salud',
        ),
        migrations.DeleteModel(
            name='Motivo_Atencion',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='residencia',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='ocupacion',
        ),
        migrations.DeleteModel(
            name='Oposicion_Donacion',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='nacionalidad',
        ),
        migrations.DeleteModel(
            name='Paciente_Discapacidad',
        ),
        migrations.DeleteModel(
            name='Paciente_Pais',
        ),
        migrations.DeleteModel(
            name='Via_Ingreso_Servicio_Salud',
        ),
        migrations.DeleteModel(
            name='Voluntad_Anticipada',
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ['nombre'], 'verbose_name': 'País', 'verbose_name_plural': 'Paises'},
        ),
        migrations.RemoveField(
            model_name='pais',
            name='id',
        ),
        migrations.AlterField(
            model_name='pais',
            name='codigo_iso',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('^[A-Za-z0-9]{3}$', 'El nombre debe tener mínimo 3 caracteres alfanuméricos.')], verbose_name='Código ISO 3166-1 del País'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('^[A-Za-z0-9]{3}$', 'El nombre debe tener mínimo 3 caracteres alfanuméricos.')], verbose_name='Nombre del País'),
        ),
        migrations.DeleteModel(
            name='Discapacidad',
        ),
        migrations.DeleteModel(
            name='Etnia',
        ),
        migrations.DeleteModel(
            name='Municipio',
        ),
        migrations.DeleteModel(
            name='Ocupacion',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
