# Generated by Django 5.2.7 on 2025-10-26 23:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica', '0003_delete_comunidad_etnica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='codigo_iso',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('^[A-Za-z0-9]{3}$', 'El codigo debe tener mínimo 3 caracteres alfanuméricos.')], verbose_name='Código ISO 3166-1 del País'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]$', 'El nombre debe tener mínimo 3 caracteres alfanuméricos.')], verbose_name='Nombre del País'),
        ),
    ]
