# Generated by Django 5.2.7 on 2025-10-26 23:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica', '0004_alter_pais_codigo_iso_alter_pais_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(200)], verbose_name='Nombre del País'),
        ),
    ]
